version: '3.5'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
    volumes:
      - ./server:/server
      - /server/node_modules
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/client
      - /client/node_modules
  